### PR TITLE
Add CLI

### PR DESCRIPTION
**Pull request by lukyth**
Early submitted PR for a discussion space 😂 

_TODO_
- [x] Make it work with files
- [x] Make it work with glob
- [x] Make it work with directories
- [x] Add an instruction
- [x] Use local installation if possible

### CODE REVIEW

**Comment by lukyth** [comment]
Should this support for directories (like `./`, `src/`) as well? It seems that some ([ESLint](https://github.com/eslint/eslint), [JSCS](https://github.com/jscs-dev/node-jscs)) are supporting it, and some ([Standard](https://github.com/feross/standard), [Prettier](https://github.com/jlongster/prettier), [XO](https://github.com/sindresorhus/xo)) aren't.

**Comment by dtinth** [comment]
@lukyth Directory support would be a nice addition, because we can do this in our CI:

```
prettier-standard-formatter src && git diff --quiet
```

instead of having to write `src/**/*.js`.

But I think that’s optional.

**Comment by lukyth** [comment]
All the features I can think of are done! 🎉

This's my first time working on a CLI. Please review, and feel free to leave any comment! 😉

**Review by dtinth — APPROVED** [review]
The code looks really well-polished! 👍 

Nice work!!

**Pull request merged**
